/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'

const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/enquire': typeof EnquireRoute
  '/heritage': typeof HeritageRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/enquire': typeof EnquireRoute
  '/heritage': typeof HeritageRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/enquire': typeof EnquireRoute
  '/heritage': typeof HeritageRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/craftsmanship'
    | '/enquire'
    | '/heritage'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/collections/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/craftsmanship'
    | '/enquire'
    | '/heritage'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/collections'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/craftsmanship'
    | '/enquire'
    | '/heritage'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/collections/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  EnquireRoute: typeof EnquireRoute
  HeritageRoute: typeof HeritageRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  EnquireRoute: EnquireRoute,
  HeritageRoute: HeritageRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
