/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminEnquiriesIndexRouteImport } from './routes/admin.enquiries.index'
import { Route as AdminJournalIndexRouteImport } from './routes/admin.journal.index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsImportRouteImport } from './routes/admin.products.import'
import { Route as AdminTestimonialsIndexRouteImport } from './routes/admin.testimonials.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/admin/categories/',
  path: '/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesIndexRoute = AdminEnquiriesIndexRouteImport.update({
  id: '/admin/enquiries/',
  path: '/admin/enquiries/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalIndexRoute = AdminJournalIndexRouteImport.update({
  id: '/admin/journal/',
  path: '/admin/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsImportRoute = AdminProductsImportRouteImport.update({
  id: '/admin/products/import',
  path: '/admin/products/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsIndexRoute = AdminTestimonialsIndexRouteImport.update({
  id: '/admin/testimonials/',
  path: '/admin/testimonials/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/enquire': typeof EnquireRoute
  '/heritage': typeof HeritageRoute
  '/admin/login': typeof AdminLoginRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/products/import': typeof AdminProductsImportRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/enquiries/': typeof AdminEnquiriesIndexRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/enquire': typeof EnquireRoute
  '/heritage': typeof HeritageRoute
  '/admin/login': typeof AdminLoginRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/admin/products/import': typeof AdminProductsImportRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/enquiries': typeof AdminEnquiriesIndexRoute
  '/admin/journal': typeof AdminJournalIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/testimonials': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/enquire': typeof EnquireRoute
  '/heritage': typeof HeritageRoute
  '/admin/login': typeof AdminLoginRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/products/import': typeof AdminProductsImportRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/enquiries/': typeof AdminEnquiriesIndexRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/craftsmanship'
    | '/enquire'
    | '/heritage'
    | '/admin/login'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/collections/'
    | '/journal/'
    | '/admin/products/import'
    | '/admin/categories/'
    | '/admin/enquiries/'
    | '/admin/journal/'
    | '/admin/products/'
    | '/admin/testimonials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/craftsmanship'
    | '/enquire'
    | '/heritage'
    | '/admin/login'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/admin'
    | '/collections'
    | '/journal'
    | '/admin/products/import'
    | '/admin/categories'
    | '/admin/enquiries'
    | '/admin/journal'
    | '/admin/products'
    | '/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/craftsmanship'
    | '/enquire'
    | '/heritage'
    | '/admin/login'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/collections/'
    | '/journal/'
    | '/admin/products/import'
    | '/admin/categories/'
    | '/admin/enquiries/'
    | '/admin/journal/'
    | '/admin/products/'
    | '/admin/testimonials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  EnquireRoute: typeof EnquireRoute
  HeritageRoute: typeof HeritageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  AdminProductsImportRoute: typeof AdminProductsImportRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminEnquiriesIndexRoute: typeof AdminEnquiriesIndexRoute
  AdminJournalIndexRoute: typeof AdminJournalIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminTestimonialsIndexRoute: typeof AdminTestimonialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries/': {
      id: '/admin/enquiries/'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries/'
      preLoaderRoute: typeof AdminEnquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal/': {
      id: '/admin/journal/'
      path: '/admin/journal'
      fullPath: '/admin/journal/'
      preLoaderRoute: typeof AdminJournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/import': {
      id: '/admin/products/import'
      path: '/admin/products/import'
      fullPath: '/admin/products/import'
      preLoaderRoute: typeof AdminProductsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials/': {
      id: '/admin/testimonials/'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminTestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  EnquireRoute: EnquireRoute,
  HeritageRoute: HeritageRoute,
  AdminLoginRoute: AdminLoginRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  AdminProductsImportRoute: AdminProductsImportRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminEnquiriesIndexRoute: AdminEnquiriesIndexRoute,
  AdminJournalIndexRoute: AdminJournalIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminTestimonialsIndexRoute: AdminTestimonialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
